---
title: "Creating shape file cumulative daily covid case Indonesia"
output: html_notebook
---


#libraries
```{r}
library(tidyverse)  # Modern data science workflow
library(sf)         # Simple features for R
library(tmap)       # Thematic Maps
```

#import non spatial data
```{r}
library(readr)
covid <- read_delim("D:/Mygithub/data-indonesia-covid19/Daily case COVID-19_Indonesia.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
View(covid)
```

#import shape file
```{r}
map <- read_sf("province border.shp")
```

```{r}
glimpse(map)
```


# Merge non spatial and spatial data
```{r}
covid_map <- inner_join(
  covid,
  map,
  by = "ID"
)
```


#import population data

```{r}
library(readr)
pop <- read_delim("population.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
View(pop)
```

# Merge covid_mp with population data
```{r}
covid_map <- inner_join(
  covid_map,
  pop,
  by = "ID"
)
```


## Keep data as sf object

- Keep the data as sf class, so we will not lose the coodinate system

```{r}
covid_map <- st_as_sf(covid_map)
```

```{r}
glimpse(covid_map)
```


# Plot Thematic Maps
## Quick Map 

- A quick map of the 19 June case

```{r}
qtm(covid_map, fill = "19-Jun")
```

- A quick map of the 19 June case

```{r}
qtm(covid_map, fill = "pop2020")
```

#save the shape file
```{r}
st_write(covid_map, "covid_map.shp")
```

